src/Entity/Driver.php
<?php

namespace App\Entity;

use App\Repository\DriverRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=DriverRepository::class)
 * @Vich\Uploadable()
 */
class Driver
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes="image/jpeg"
     * )
     * @Vich\UploadableField(mapping="driver_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="integer")
     */
    private $years_of_experience;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $languages;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }


    public function getYearsOfExperience(): ?int
    {
        return $this->years_of_experience;
    }

    public function setYearsOfExperience(int $years_of_experience): self
    {
        $this->years_of_experience = $years_of_experience;

        return $this;
    }

    public function getLanguages(): ?string
    {
        return $this->languages;
    }

    public function setLanguages(string $languages): self
    {
        $this->languages = $languages;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Driver
     */
    public function setFilename(?string $filename): Driver
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Driver
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile): Driver
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile){
            $this->updated_at=new \DateTime('now');
        }
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }



}

templates/pages/chalets.html.twig
{% extends '_base.html.twig' %}
{% block body %}
{% endblock %}

templates/pages/contact.html.twig
{% extends '_base.html.twig' %}
{% block body %}
<!-- Start Contact -->
<section class="contact-map style-1">

    <!-- Start Map Contact -->
    <div id="map-contact1"></div>
    <!-- End Map Contact -->

    <div class="container">

        <!-- Start Contact-Info -->
        <div class="col-lg-4 col-lg-offset-1 col-md-4 col-md-offset-1">
            <div class="contact-info">
                <ul class="custom-list contact-info-details">
                    <li><b>Concierge HQ</b></li>
                    <li>121 King Street, Melbourne</li>
                    <li>Victoria 3000 Australia</li>
                    <li>Phone: +61 3 8376 6284</li>
                    <li>example@example.com</li>
                </ul>
            </div>
        </div>
        <!-- End Contact-Info -->

        <!-- Start Contact-Form -->
        <div class="col-lg-6 col-lg-offset-1 col-md-6 col-md-offset-1 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <div class="contact-form">
                <h5 class="contact-form-title">Send us a message</h5>
                <img src="{{ asset('img/divisor.png') }}" alt="" class="divisor">
                <form action="{{ path('home') }}" class="default-form">
                    <p class="alert-message warning"><i class="ico fa fa-exclamation-circle"></i> All fields are required!</p>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <p class="form-row">
                                <input class="required" type="text" placeholder="Name">
                            </p>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <p class="form-row">
                                <input class="required" type="text" placeholder="Phone">
                            </p>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <p class="form-row">
                                <input class="required" type="text" placeholder="Email">
                            </p>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <p class="form-row">
                                <input class="required" type="text" placeholder="Topic">
                            </p>
                        </div>
                    </div>
                    <p class="form-row">
                        <textarea name="message" placeholder="How we can help?"></textarea>
                    </p>
                    <button class="btn dark">Send Message</button>
                </form>
            </div>
        </div>
        <!-- End Contact-Form -->

    </div>
</section>
<!-- End Contact -->
{% endblock %}

templates/pages/drivers.html.twig
{% extends '_base.html.twig' %}
{% block title 'Ma Conciergerie' %}
{% block body %}

<!-- Start Drivers -->
<section class="drivers">
    <div class="container">
        <div class="row">

            <!-- Start Preamble -->
            <div class="col-lg-12 preamble">
                <h3>Our Drivers</h3>
                <img src="{{ asset('img/divisor.png') }}" alt="" class="divisor">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue, pede vitae dapibus aliquet, elit magna vulputate arcu, vel tempus metus leo non est.</p>
            </div>
            <!-- End Preamble -->

            <!-- Start Drivers-List -->
            <div class="col-lg-6 col-md-6 col-sm-6">
                <ul class="custom-list drivers-profile-list layout-list">
                    {% for driver in drivers %}
                    <li class="driver-profile">
                        <div class="overlay">
                            <div class="thumb driver-thumb">
                                {% if driver.filename %}
                                    <img src="{{ vich_uploader_asset(driver, 'imageFile') | imagine_filter('thumb')}}" alt="" style="width: 100%; height: auto">
                                {% else %}
                                    <img src="{{ 'images/driver/empty.jpg' | imagine_filter('thumb')}}" alt="" style="width: 100%; height: auto">
                                {% endif %}
                            </div>

                            <div class="content driver-profile-content">
                                <header class="driver-profile-header">
                                    <h5>{{ driver.lastname }} {{ driver.firstname }}</h5>
                                    <span>chauffeu</span>
                                </header>
                                <ul class="properties driver-profile-properties">
                                    <li>Years of experience<strong>{{ driver.yearsOfExperience }}</strong></li>
                                    <li>Languages <strong>{{ driver.languages }}</strong> </li>
                                </ul>
                            </div>
                        </div>
                        {% endfor %}

                    </li>

                </ul>
            </div>
            <!-- End Drivers-List -->
        </div>
    </div>
</section>
<!-- End Drivers -->
{% endblock %}

templates/pages/hotels.html.twig
{% extends '_base.html.twig' %}
{% block body %}
<!-- Start Section Fleets -->
<section class="fleets">
    <div class="container">
        <div class="row">

            <!-- Start Filters -->
            <div class="col-lg-12 filter">
                <aside class="fleets-filters horizontal col-row">

                    <!-- Start Propeties Search Basic -->
                    <div class="fleets-search-basic">

                        <!-- Start Propities Search Type -->
                        <div class="default-form fleets-search-type">
                            <h5 class="filter-title">Vechicle Type</h5>
                            <span class="radio-input">
                    <input id="yachts" type="radio" name="filter_type" value="yachts" checked="checked">
                    <label for="yachts">Yachts</label>
                  </span>
                            <span class="radio-input">
                    <input id="jetplanes" type="radio" name="filter_type" value="jetplanes">
                    <label for="jetplanes">Jet Planes</label>
                  </span>
                            <span class="radio-input">
                    <input id="luxcars" type="radio" name="filter_type" value="luxurycars">
                    <label for="luxcars">Luxury Cars</label>
                  </span>
                            <span class="radio-input">
                    <input id="cars" type="radio" name="filter_type" value="cars">
                    <label for="cars">Cars</label>
                  </span>
                        </div>
                        <!-- End Propities Search Type -->

                        <form action="{{ path('home') }}" class="default-form">

                            <!-- Start Propities Availability -->
                            <div class="fleets-availability">
                                <h5 class="filter-title">Available on</h5>
                                <p class="form-row">
                      <span class="hire-input calendar">
                        <input type="text" name="hireOn" placeholder="Hire On" data-dateformat="m/d/y">
                        <i class="fa fa-calendar"></i>
                      </span>
                                </p>
                                <p class="form-row">
                      <span class="return-input calendar">
                        <input type="text" name="Retun On" placeholder="Return On" data-dateformat="m/d/y">
                        <i class="fa fa-calendar"></i>
                      </span>
                                </p>
                            </div>
                            <!-- End Propities Availability -->

                        </form>
                    </div>
                    <!-- End Propeties Search Basic -->

                    <!-- Start Properties Search Filter -->
                    <div class="fleets-search-filter">
                        <form action="{{ path('home') }}" class="default-form">

                            <!-- Start Propities Capacity -->
                            <div class="fleets-capacity">
                                <h5 class="filter-title">Capacity (People)</h5>
                                <p class="form-row">
                    <span class="people select-box">
                      <select name="people" data-placeholder="People">
                        <option>People</option>
                        <option value="1">2</option>
                        <option value="2">3</option>
                        <option value="3">4</option>
                      </select>
                    </span>
                                </p>
                            </div>
                            <!-- End Propities Capacity -->

                            <!-- Start Price Range -->
                            <div class="slider-range-container cleafix">
                                <h5 class="filter-title">Price Range</h5>
                                <div class="slider-range" data-min="2000" data-max="100000" data-step="2000" data-default-min="2000" data-default-max="50000" data-currency="$"></div>
                                <div class="clearfix">
                                    <input type="text" class="range-from" value="$2000">
                                    <input type="text" class="range-to" value="$50000">
                                </div>
                            </div>
                            <!-- End Price Range -->

                            <!-- Start Additional-Services -->
                            <div class="fleets-additional-services">
                                <h5 class="filter-title">Additional Services</h5>
                                <ul class="custom-list additional-filter-list clearfix">
                                    <li>
                        <span class="checkbox-input">
                          <input type="checkbox" id="additional-filter-all-inclusive">
                          <label for="additional-filter-all-inclusive">All Inclusive</label>
                        </span>
                                    </li>
                                    <li>
                        <span class="checkbox-input">
                          <input type="checkbox" id="additional-filter-2way-flight" checked="checked">
                          <label for="additional-filter-2way-flight">2 Way Flight</label>
                        </span>
                                    </li>
                                    <li>
                        <span class="checkbox-input">
                          <input type="checkbox" id="additional-filter-business-package">
                          <label for="additional-filter-business-package">Business Package</label>
                        </span>
                                    </li>
                                </ul>
                            </div>
                            <!-- End Additional-Services -->

                        </form>

                        <div class="filter-btn">
                            <form action="{{ path('home') }}" class="default-form">
                                <a href="#" class="btn dark">Filter Now</a>
                            </form>
                        </div>
                    </div>
                    <!-- End Propeties Search Filter -->

                </aside>
            </div>
            <!-- End Filters -->

            <!-- Start Fleets-Listing-Header -->
            <div class="col-lg-12">
                <div class="fleets-listing-header clearfix">
                    <h5>Available Rooms</h5>
                    <ul class="custom-list fleets-listing-pagination">
                        <li class="prev"><a href="#">Previous</a></li>
                        <li class="number"><a href="#" class="active">1</a></li>
                        <li class="number"><a href="#">2</a></li>
                        <li class="number"><a href="#">3</a></li>
                        <li class="number"><a href="#">4</a></li>
                        <li class="next"><a href="#">Next</a></li>
                    </ul>
                </div>
            </div>
            <!-- End Fleets-Listing-Header -->

            <!-- Start Fleets List -->
            <div class="col-lg-3 col-md-4 col-sm-6 fleet-grid layout-grid">
                <div class="thumb fleet-thumb">
                    <div class="overlay">
                        <img src="{{ asset('img/fleet-vechicle6.jpg') }}" alt="">
                        <div class="overlay-shadow">
                            <div class="overlay-content">
                                <a href="fleet_unit_details.html" class="btn light">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="fleet-vechicle-content">
                    <header class="fleet-vechicle-header">
                        <h5><a href="fleet_unit_details.html">Airbus A380</a></h5>
                        <span>Starting from $899</span>
                    </header>
                    <ul class="custom-list fleet-vechicle-properties">
                        <li>Vehicle Age <strong>4</strong></li>
                        <li>Capacity (People) <strong>16+4</strong> </li>
                        <li>Max Speed <strong>1 Ma</strong> </li>
                        <li>Fuel Capacity<strong>8 hours</strong></li>
                        <li>Max Weight<strong>2t</strong></li>
                        <li>Pilots (Min.)<strong>2</strong></li>
                    </ul>
                </div>
            </div>
            <!-- End Fleets List -->

        </div>
    </div>
</section>
<!-- End Section Fleets -->
{% endblock %}